/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as NominateRouteImport } from './routes/nominate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AccreditationRouteImport } from './routes/accreditation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const NominateRoute = NominateRouteImport.update({
  id: '/nominate',
  path: '/nominate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccreditationRoute = AccreditationRouteImport.update({
  id: '/accreditation',
  path: '/accreditation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accreditation': typeof AccreditationRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/nominate': typeof NominateRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue': typeof VenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accreditation': typeof AccreditationRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/nominate': typeof NominateRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue': typeof VenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accreditation': typeof AccreditationRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/nominate': typeof NominateRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue': typeof VenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accreditation'
    | '/categories'
    | '/contact'
    | '/events'
    | '/nominate'
    | '/schedule'
    | '/sitemap.xml'
    | '/venue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accreditation'
    | '/categories'
    | '/contact'
    | '/events'
    | '/nominate'
    | '/schedule'
    | '/sitemap.xml'
    | '/venue'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accreditation'
    | '/categories'
    | '/contact'
    | '/events'
    | '/nominate'
    | '/schedule'
    | '/sitemap.xml'
    | '/venue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccreditationRoute: typeof AccreditationRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  NominateRoute: typeof NominateRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenueRoute: typeof VenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominate': {
      id: '/nominate'
      path: '/nominate'
      fullPath: '/nominate'
      preLoaderRoute: typeof NominateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accreditation': {
      id: '/accreditation'
      path: '/accreditation'
      fullPath: '/accreditation'
      preLoaderRoute: typeof AccreditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccreditationRoute: AccreditationRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  NominateRoute: NominateRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenueRoute: VenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
